<a href="https://colab.research.google.com/github/kjh1696/DeepLearning/blob/main/Mininet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
x = torch.randn(100,3)
layer = nn.Linear(3,5)

print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.5024, -0.0013,  0.4260],
        [ 0.2895, -0.4503, -0.2050],
        [ 0.3773,  0.0653,  0.0514],
        [ 0.2288, -0.5687,  0.4852],
        [ 0.0516,  0.1794,  0.1564]], requires_grad=True)
Parameter containing:
tensor([ 0.3770, -0.2038,  0.0150,  0.3963,  0.3379], requires_grad=True)


In [4]:
x = torch.randn(2,5)
layer = nn.ReLU()
print(x)
print(layer(x)) # 음수면 0으로 음수가 아니라면 그대로 출력

tensor([[-0.4025, -1.3169, -0.2986,  0.8208, -0.9130],
        [-1.0388,  1.0487,  0.2258, -0.5879, -0.4416]])
tensor([[0.0000, 0.0000, 0.0000, 0.8208, 0.0000],
        [0.0000, 1.0487, 0.2258, 0.0000, 0.0000]])


In [6]:
layer = nn.BatchNorm1d(3)

print(layer.weight)
print(layer.bias)

x = torch.randn(5,3)
print(x)
print(layer(x))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[ 0.3482, -0.4196, -0.2207],
        [ 0.1231,  0.5379, -1.1356],
        [ 0.2627, -1.1078, -0.1815],
        [ 0.4913,  1.4941, -0.2671],
        [ 0.3904,  1.9861, -0.5429]])
tensor([[ 0.2017, -0.7971,  0.6984],
        [-1.6103,  0.0345, -1.8690],
        [-0.4868, -1.3947,  0.8083],
        [ 1.3538,  0.8650,  0.5682],
        [ 0.5415,  1.2923, -0.2059]], grad_fn=<NativeBatchNormBackward0>)


In [7]:
x = torch.randn(3,7)
drop = nn.Dropout(p = 0.1) # 구현에서 p는 죽일 확률
print(x)
print(drop(x) * (1-0.3)) # 구현은 반대로 훈련 때 1/살릴 확률을 곱하고 테스트 때는 그대로
drop.eval()
print(drop(x))

tensor([[-0.6285,  0.5020,  0.3636, -0.1492,  0.7268,  0.5209,  0.4227],
        [ 0.2452,  0.5089,  0.5448,  0.4363,  0.2402,  0.5725,  0.0233],
        [-1.1663,  0.3536, -0.9961,  0.4814,  1.1174,  0.3688,  0.1488]])
tensor([[-0.4889,  0.3904,  0.2828, -0.1161,  0.5653,  0.4052,  0.3287],
        [ 0.1907,  0.3958,  0.4237,  0.3394,  0.1869,  0.4453,  0.0181],
        [-0.9071,  0.2751, -0.7747,  0.3744,  0.8691,  0.2868,  0.0000]])
tensor([[-0.6285,  0.5020,  0.3636, -0.1492,  0.7268,  0.5209,  0.4227],
        [ 0.2452,  0.5089,  0.5448,  0.4363,  0.2402,  0.5725,  0.0233],
        [-1.1663,  0.3536, -0.9961,  0.4814,  1.1174,  0.3688,  0.1488]])
